// app/models/Data.js
import mongoose from "mongoose";

const OrderSchema = new mongoose.Schema({
  slNo: { type: String, required: true },
  customerName: { type: String, required: true },
  branchId: { type: String, required: true },
  branchName: { type: String, required: true },
  organization: { type: String, required: true },
  customerPoNo: { type: String, required: true },
  poDate: { type: Date },
  orderFor: { String, enum: ["SYSTEM", "BATTERY", "SYSTEM & BATTERY", "RACK", "OTHERS" ] },
  isBuybackAvailable: { type: String, enum: ["YES", "NO", ""] },
  indentNo: String,
  indentDate: Date,
  sapCode: String,
  atmId: String,
  state: String,
  deliveryAddress: String,
  pinCode: String,
  siteContactName: String,
  siteContactNumber: String,
  systemDescription: String,
  systemQuantity: Number,
  batteryDescription: String,
  batteryQuantity: Number,
  buybackDescription: String,
  buybackQuantity: Number,
  scheduledDispatchDate: Date,
  actualDispatchDate: Date,
  invoiceNo: String,
  invoiceDate: Date,
  deliveryChallanNo: String,
  deliveryChallanDate: Date,
  transporterDetails: String,
  docketNo: String,
  transporterContactDetails: String,
  plannedDeliveryDate: Date,
  actualDeliveryDate: Date,
  installationPlannedDate: Date,
  actualInstallationDate: Date,
  installationDoneBy: String,
  serialNo: String,
  installationReportNo: String,
  buybackReceived: { type: String, enum: ["RECEIVED", "NOT RECEIVED", "PARTIAL RECEIVED", ""] },
  buybackReceivedDate: Date,
  receivedBuybackDetailsWithQty: String,
  paymentStatus: { type: String, enum: ["COMPLETED", "PENDING", "PARTIAL RECEIVED", ""] },
  lastPaymentReceivedDate: Date,
  paymentAmount: Number,
  paymentDetails: String,
  remarks: String,
  createdBy: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
  updatedBy: String,
  updatedAt: Date,
});

export default mongoose.models.Order || mongoose.model("Order", OrderSchema);
